import { $ } from "bun";
import { mkdirSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { readMigrationFiles } from "drizzle-orm/migrator";

type Arch = "x64" | "arm64";
type Platform = "linux" | "darwin" | "windows";

const PACKAGE_ROOT = path.resolve(import.meta.dir, "..");
const CLIENT_DIST_DIR = path.join(PACKAGE_ROOT, "dist", "client");
const GENERATED_ASSETS_MODULE = path.join(PACKAGE_ROOT, "dist", "embedded-client-assets.ts");
const MIGRATIONS_DIR = path.join(PACKAGE_ROOT, "migrations");
const GENERATED_MIGRATIONS_MODULE = path.join(PACKAGE_ROOT, "dist", "embedded-migrations.ts");

function normalizeArch(value: string): Arch {
  switch (value.toLowerCase()) {
    case "x64":
    case "amd64":
    case "x86_64":
      return "x64";
    case "arm64":
    case "aarch64":
      return "arm64";
    default:
      throw new Error(`Unsupported architecture: ${value}`);
  }
}

function normalizePlatform(value: string): Platform {
  switch (value.toLowerCase()) {
    case "linux":
      return "linux";
    case "darwin":
    case "mac":
    case "macos":
      return "darwin";
    case "windows":
    case "win32":
      return "windows";
    default:
      throw new Error(`Unsupported platform: ${value}`);
  }
}

function resolveTarget(): string {
  const arch = normalizeArch(process.env.BUN_BINARY_ARCH ?? process.arch);
  const explicitTarget = process.env.BUN_BINARY_TARGET;

  if (!explicitTarget) {
    // Default to the current machine architecture/platform.
    return `bun-${normalizePlatform(process.platform)}-${arch}-modern`;
  }

  if (explicitTarget.startsWith("bun-")) {
    return explicitTarget;
  }

  const platform = normalizePlatform(explicitTarget);
  return `bun-${platform}-${arch}-modern`;
}

function listFilesRecursively(dir: string, baseDir: string = dir): string[] {
  const files: string[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const entryPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listFilesRecursively(entryPath, baseDir));
      continue;
    }

    if (entry.isFile()) {
      const relativePath = path.relative(baseDir, entryPath).split(path.sep).join("/");
      files.push(relativePath);
    }
  }

  return files;
}

function generateEmbeddedAssetsModule(): void {
  const assetFiles = listFilesRecursively(CLIENT_DIST_DIR).sort((a, b) => a.localeCompare(b));
  if (assetFiles.length === 0) {
    throw new Error(`No files found in ${CLIENT_DIST_DIR}. Run vite build first.`);
  }

  const lines: string[] = ["// Auto-generated by scripts/build.ts. Do not edit manually.", ""];

  for (const [index, file] of assetFiles.entries()) {
    lines.push(`import asset${index} from ${JSON.stringify(`./client/${file}`)} with { type: "file" };`);
  }

  lines.push("");
  lines.push("export const embeddedClientAssets: Record<string, string> = {");
  for (const [index, file] of assetFiles.entries()) {
    lines.push(`  ${JSON.stringify(`/${file}`)}: asset${index},`);
  }
  lines.push("};");
  lines.push("");

  mkdirSync(path.dirname(GENERATED_ASSETS_MODULE), { recursive: true });
  writeFileSync(GENERATED_ASSETS_MODULE, lines.join("\n"));

  console.log(`[server build] Embedded ${assetFiles.length} static assets`);
}

function generateEmbeddedMigrationsModule(): void {
  const migrations = readMigrationFiles({ migrationsFolder: MIGRATIONS_DIR });
  const lines: string[] = [
    "// Auto-generated by scripts/build.ts. Do not edit manually.",
    'import type { MigrationMeta } from "drizzle-orm/migrator";',
    "",
    `export const embeddedMigrations = ${JSON.stringify(migrations, null, 2)} satisfies MigrationMeta[];`,
    "",
  ];

  mkdirSync(path.dirname(GENERATED_MIGRATIONS_MODULE), { recursive: true });
  writeFileSync(GENERATED_MIGRATIONS_MODULE, lines.join("\n"));

  console.log(`[server build] Embedded ${migrations.length} Drizzle migrations`);
}

const target = resolveTarget();
generateEmbeddedAssetsModule();
generateEmbeddedMigrationsModule();
console.log(`[server build] Using binary target: ${target}`);

await $`bun build --compile --target ${target} --outfile dist/agentlogs-server ./standalone.ts`;
